src/authentic/urls.py
from django.urls import path
from .views import(
    loginPage,
    logoutUser,
)
app_name = 'authentic'

urlpatterns = [
    path('login/', loginPage, name='login'),
    path('logout', logoutUser, name='logout'),
]

src/partners/urls.py
from django.urls import path
from .views import (
    supplierTable,
    supplierDetail,
    supplierDelete,

    entityTypeTable,
    entityTypeDetail,
    entityTypeDelete,

    clientTable,
    clientDetail,
    clientDelete,
)
app_name = 'partners'

urlpatterns = [
    # suppliers
    path('suppliers/', supplierTable, name='suppliers'),
    path('supplier/<str:pk>/', supplierDetail, name='supplier'),
    path('supplier/delete/<str:pk>', supplierDelete, name='delete-supplier'),

    #entity Type
    path('entity-type/', entityTypeTable, name='entity-types'),
    path('entity-type/<str:pk>/', entityTypeDetail, name='entity-type'),
    path('entity-type/delete/<str:pk>/', entityTypeDelete, name='delete-entity-type'),


    #clients
    path('clients/', clientTable, name='clients'),
    path('client/<str:pk>/', clientDetail, name='client'),
    path('client/delete/<str:pk>/', clientDelete, name='delete-client'),



]

src/product/urls.py
from django.urls import path
from .views import (
    productTable,
    productDetail,
    productDelete,

    categoryTable,
    categoryDetail,
    categoryDelete,
    
    measurementTable,
    measurementDetail,
    measurementDelete,
)
app_name = 'product'

urlpatterns = [
    # products
    path('', productTable, name='table'),
    path('detail/<str:pk>/', productDetail, name='detail'),
    path('delete/<str:pk>/', productDelete, name='delete'),

    #categories
    path('categories/', categoryTable, name='categories'),
    path('category/<str:pk>/', categoryDetail, name='category'),
    path('category/delete/<str:pk>/', categoryDelete, name='category-delete'),

    #measurement
    path('measurements/', measurementTable, name='measurements'),
    path('measurement/<str:pk>/', measurementDetail, name='measurement'),
    path('measurement/delete/<str:pk>/', measurementDelete, name='measurement-delete'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static
from .settings import IS_PRODUCTION

urlpatterns = [
    path('', include('dashboard.urls')),
    path('authentic/', include('authentic.urls')),
    path('product/', include('product.urls')),
    path('stock/', include('stock.urls')),
    path('partners/', include('partners.urls')),
    path('transactions/', include('transactions.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)


if not IS_PRODUCTION:
    urlpatterns += [
        path('gest/admin/', admin.site.urls),
    ]

src/stock/urls.py
from django.urls import path
from .views import (
    stockInfo,
)
app_name = 'stock'

urlpatterns = [
    path('', stockInfo, name='info'),
]

src/templates/alerts.html
<!-- Bootstrap Alerts rendered message under navbar -->
<div class="row text-center">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            <!--span aria-hidden="true">&times;</span-->
        </button>
        {{ message | safe }}
    </div>
    {% endfor %}
</div>

src/templates/delete.html
{% extends 'main.html' %}

{% block content %}
    <div class="container min-vh-100 d-flex justify-content-center align-items-center p-2">
        <div class="card">
            <div class="card-action text-end">
                <a href="{{request.META.HTTP_REFERER}}" class="btn btn-warning"><i class="fa-solid fa-xmark"></i></a>
            </div>
            <hr>
            <div class="card-body">
                <div class="p-3 m-1">
                    Do you want to delete <strong>{{obj.name}}</strong> ??
                    <hr>
                    <form action="" method="POST">
                        {% csrf_token %}

                        <div class="form__action text-center">
                            <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Yes<span
                                    class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/footer.html
{% if request.user.is_authenticated %}
<footer class="navbar bottom navbar-dark bg-dark text-white">
    <div class="container-fluid">
        <div class="col-4 text-center">
            <small class=" copyright mb-0">
                    &copy; Copyright 2024 Motcho
            </small>
        </div>
        <div class="col-4 text-center">
            <!-- Search with q -->
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-warning" type="submit">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </button>
            </form>
        </div>
        <div class="socials col-4 text-center">
            <ul class="mb-0 list-inline">
                <li class="list-inline-item">
                    <a href="#" class="btn btn-outline-info btn-sm">
                        <i class="fa-brands fa-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn btn-outline-danger btn-sm">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn btn-outline-secondary btn-sm">
                        <i class="fa-brands fa-github"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>
<!-- End Footer -->
{% endif %}

src/templates/main.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="dark">

<head>
    <!-- Meta data -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Tags -->
    <title>DataMotive{% block title %} {% endblock title %}</title>
    {% block styles %} {% endblock styles %}

    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'styles/index.css' %}">
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link rel="stylesheet" href="{% static 'styles/dashboard.css' %}">

    <!-- Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/af0ff4f1fc.js" crossorigin="anonymous"></script>

    <!-- Chart Js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
    <div class="wrapper">
        <div class="main">
            {% include 'navbar.html' %}
            {% include 'alerts.html' %}
            {% block content %}
            {% endblock content %}
            {% include 'footer.html' %}
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block scripts %} {% endblock scripts %}
</body>

</html>

src/templates/navbar.html
{% if request.user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <a class="navbar-brand mx-4" href="{% url 'dashboard:home' %}">DataMotive</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item mx-3">
                    <a class="nav-link active" aria-current="page" href="{% url 'stock:info' %}">
                        <i class="fa-solid fa-boxes px-2"></i>
                        My Stock
                    </a>
                </li>
                <!-- Dropdown Products -->
                <li class="nav-item dropdown mx-3">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-box px-2"></i>
                        Products
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <!-- Product Table -->
                        <li>
                            <a class="dropdown-item" href="{% url 'product:table' %}">
                                <i class="fa-solid fa-table px-2"></i>
                                Table
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <!-- Product Category -->
                        <li>
                            <a class="dropdown-item" href="{% url 'product:categories' %}">
                                <i class="fa-solid fa-list px-2"></i>
                                Categories
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <!-- Product Category -->
                        <li>
                            <a class="dropdown-item" href="{% url 'product:measurements' %}">
                                <i class="fa-solid fa-ruler px-2"></i>
                                Measurement
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- Dropdown Partners -->
                <li class="nav-item dropdown mx-3">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-users px-2"></i>
                        Partners
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <!-- Partners - Clients -->
                        <li>
                            <a class="dropdown-item" href="{% url 'partners:clients' %}">
                                <i class="fa-solid fa-person px-2"></i>
                                Clients
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <!-- Partners-Suppliers -->
                        <li>
                            <a class="dropdown-item" href="{% url 'partners:suppliers' %}">
                                <i class="fa-solid fa-boxes-packing px-1"></i>
                                Suppliers
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <!-- Entity Type -->
                        <li>
                            <a class="dropdown-item" href="{% url 'partners:entity-types' %}">
                                <i class="fa-solid fa-clipboard px-2"></i>
                                Entity Type
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- Dropdown Transactions -->
                <li class="nav-item dropdown mx-3">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-repeat px-2"></i>
                        Transactions
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <!-- Transactions - Sales -->
                        <li>
                            <a class="dropdown-item" href="{% url 'transactions:sales' %}">
                                <i class="fa-solid fa-hand-holding-dollar px-2"></i>
                                Sales
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <!-- Transactions - Purchases -->
                        <li>
                            <a class="dropdown-item" href="{% url 'transactions:purchases' %}">
                                <i class="fa-solid fa-cart-arrow-down px-2"></i>
                                Purchases
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Logout -->
            <div class="d-flex">
                <a class="btn btn-outline-secondary btn-md mx-2" href="{% url 'authentic:logout' %}">
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                </a>
            </div>
        </div>
    </div>
</nav>
{% endif %}

src/templates/pagination.html
<!-- Pagination -->
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center mt-4">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link text-warning" href="?page=1" aria-label="First">
                <span aria-hidden="true">&laquo;&laquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link text-warning" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link text-dark bg-warning">{{ num }}</span>
                </li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link text-warning" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link text-warning" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link text-warning" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
<!-- End Pagination -->