src/partners/urls.py
from django.urls import path
from .views import (
    supplierTable,
    supplierDetail,
    supplierDelete,

    entityTypeTable,
    entityTypeDetail,
    entityTypeDelete,

    clientTable,
    clientDetail,
    clientDelete,
)
app_name = 'partners'

urlpatterns = [
    # suppliers
    path('suppliers/', supplierTable, name='suppliers'),
    path('supplier/<str:pk>/', supplierDetail, name='supplier'),
    path('supplier/delete/<str:pk>', supplierDelete, name='delete-supplier'),

    #entity Type
    path('entity-type/', entityTypeTable, name='entity-types'),
    path('entity-type/<str:pk>/', entityTypeDetail, name='entity-type'),
    path('entity-type/delete/<str:pk>/', entityTypeDelete, name='delete-entity-type'),


    #clients
    path('clients/', clientTable, name='clients'),
    path('client/<str:pk>/', clientDetail, name='client'),
    path('client/delete/<str:pk>/', clientDelete, name='delete-client'),



]

src/product/urls.py
from django.urls import path
from .views import (
    productTable,
    productDetail,
    productDelete,

    categoryTable,
    categoryDetail,
    categoryDelete,
    
    measurementTable,
    measurementDetail,
    measurementDelete,
)
app_name = 'product'

urlpatterns = [
    # products
    path('', productTable, name='table'),
    path('detail/<str:pk>/', productDetail, name='detail'),
    path('delete/<str:pk>/', productDelete, name='delete'),

    #categories
    path('categories/', categoryTable, name='categories'),
    path('category/<str:pk>/', categoryDetail, name='category'),
    path('category/delete/<str:pk>/', categoryDelete, name='category-delete'),

    #measurement
    path('measurements/', measurementTable, name='measurements'),
    path('measurement/<str:pk>/', measurementDetail, name='measurement'),
    path('measurement/delete/<str:pk>/', measurementDelete, name='measurement-delete'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static
from .settings import IS_PRODUCTION

urlpatterns = [
    path('', include('dashboard.urls')),
    path('authentic/', include('authentic.urls')),
    path('product/', include('product.urls')),
    path('stock/', include('stock.urls')),
    path('partners/', include('partners.urls')),
    path('transactions/', include('transactions.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)


if not IS_PRODUCTION:
    urlpatterns += [
        path('gest/admin/', admin.site.urls),
    ]

src/transactions/urls.py
from django.urls import path
from .views import (
    purchaseTable,
    purchaseDelete,
    purchaseDetail,

    saleTable,
    saleDetail,
    saleDelete,

)
app_name = 'transactions'

urlpatterns = [
    #purchases
    path('purchases/', purchaseTable, name='purchases'),
    path('purchase/<str:pk>/', purchaseDetail, name='purchase'),
    path('purchase/delete/<str:pk>/', purchaseDelete, name='delete-purchase'),

    # sales
    path('sales/', saleTable, name='sales'),
    path('sale/<str:pk>/', saleDetail, name='sale'),
    path('sale/delete/<str:pk>/', saleDelete, name='delete-sale'),

]

src/product/models.py
from decimal import Decimal
from django.db import models
from django.core.validators import (
    MinValueValidator, MaxValueValidator,
    RegexValidator, MaxLengthValidator,
    DecimalValidator, validate_image_file_extension
)
from src.utils import generate_code
from src.validators import validate_names


class Measurement(models.Model):

    measure = models.CharField(
        max_length=100, unique=True, default='Unit',
        verbose_name='Measure'
    )

    def __str__(self):
        return f'{self.measure}'
    

class Category(models.Model):

    name = models.CharField(
        max_length=100, unique=True, default='No Name',
        validators=[validate_names],
        verbose_name='Category'
    )
    category_img = models.ImageField(
        upload_to='category', default='default_img.jpg', 
        validators=[validate_image_file_extension],
        verbose_name='Category Image', blank=True
    )

    def __str__(self):
        return f'{self.name}'
    
    def product_count(self):
        return self.products.count()
    
    def get_product(self):
        return self.products.all()

class Product(models.Model):

    name = models.CharField(
        max_length=120, unique=True,
        validators=[validate_names],
        verbose_name='Name'
    )
    ref = models.CharField(
        max_length=18, unique=True,
        validators=[RegexValidator],
        verbose_name='Ref', null=True, blank=True
    )
    description = models.TextField(
        blank=True, null=True,
        validators=[MaxLengthValidator(1000)],
        verbose_name='Description'
    )
    product_img = models.ImageField(
        upload_to='product', default='default_img.jpg',
        validators=[validate_image_file_extension],
        verbose_name='Product Image', blank=True
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL,
        verbose_name='Category', null=True,
        related_name='products'
    )
    active = models.BooleanField(
        default=True,verbose_name='Active'
    )
    measurement = models.ForeignKey(
        Measurement, on_delete=models.SET_NULL,
        verbose_name='Measurement', null=True,
        related_name='products'
    )
    price = models.DecimalField(
        max_digits=18, decimal_places=2, default=0.00,
        help_text='Value in Euros',
        validators=[DecimalValidator(18, 2)],
        verbose_name='Price'
    )
    discount = models.DecimalField(
        max_digits=3, decimal_places=0, default=0, help_text="%",
        validators=[MinValueValidator(0), MaxValueValidator(100), DecimalValidator(3, 0)],
        verbose_name='Discount', blank=True
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def final_price(self):
        if self.discount is not None or 0:
            discount_value = (float(self.price) * float(self.discount) * 0.01)
            val = float(self.price) - discount_value
            return round(val, 2)
        return round(Decimal(self.price), 2)
    
    def save(self, *args, **kwargs):
        if self.discount is None or '':
            self.discount = 0
        if self.ref is None or '':
            self.ref = generate_code()
        return super().save(*args, **kwargs)
    
    def get_suppliers(self):
        return self.suppliers.all()
    
    def get_stock_quantity(self):
        return self.in_stock.quantity
    
    def __str__(self):
        return f'{self.name} [{self.category}] ({self.final_price}€)'
    
    class Meta:
        ordering = ['id']

src/product/forms.py
from django import forms
from .models import Category, Product, Measurement


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('ref',)

class MeasurementForm(forms.ModelForm):
    class Meta:
        model = Measurement
        fields = '__all__'

src/product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Q, Sum
from django.contrib.auth.decorators import login_required
import json

from stock.models import Stock
from .models import Product, Category, Measurement
from .forms import ProductForm, CategoryForm, MeasurementForm
from src.utils import get_page_obj
from .utils import get_purchases_by_product, get_sales_by_product, get_products_by_category

# Products
@login_required(login_url='authentic:login')
def productTable(request):
    """
    View porducts,
    Contains a table with all products,
    Possibility to create new products
    Search on Navbar by: name, category, measurement and description
    """
    q = request.GET.get('q') if request.GET.get('q') is not None else ''

    product = Product
    products = Product.objects.filter(
        Q(name__icontains=q) |
        Q(category__name__icontains=q) |
        Q(measurement__measure__icontains=q) |
        Q(description__icontains=q)
    )
    page_obj = get_page_obj(products, request)


    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Stock instance is created by a signal
            messages.success(request, "Product created!")
            return redirect('product:table')
        else:
            messages.error(request, form.errors)

    context = {
        'objs':products,
        'product':product,
        'form':form,
        'page_obj':page_obj,
    }
    return render(request, 'product/products/table.html', context)

@login_required(login_url='authentic:login')
def productDetail(request, pk):
    """
    Detail view of product,
    Possibility to update product
    """
    product = get_object_or_404(Product, id=pk)
    product_purchases = get_purchases_by_product(product)
    product_sales = get_sales_by_product(product)

    stock = Stock.objects.get(product=product)
    total_quantity = Stock.objects.aggregate(total=Sum('quantity'))['total']




    form = ProductForm(instance=product)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, "Product Modified!")
            return redirect('product:detail', product.id)
        else:
            messages.error(request, form.errors)

    context = {
        'obj' : product,
        'form' : form,
        'purchases' : product_purchases,
        'sales' : product_sales,
        'product_name': product.name,
        'product_quantity': stock.quantity,
        'total_quantity' : total_quantity,

    }
    return render(request, 'product/products/detail.html', context)

@login_required(login_url='authentic:login')
def productDelete(request, pk):
    """
    Delete product
    """
    obj = get_object_or_404(Product, id=pk)
    if request.method == 'POST':
        obj.delete()
        messages.success(request, "Product Deleted!")
        return redirect('product:table')
    
    return render(request, 'delete.html', {'obj':obj})

# Categories
@login_required(login_url='authentic:login')
def categoryTable(request):
    """
    View Product Categories,
    Contains a table with all existing Categories,
    Possibility to create new Category
    Search on Navbar by: name.
    """
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    
    category = Category
    categories = Category.objects.filter(
        Q(name__icontains=q)
    )
    page_obj = get_page_obj(categories, request)

    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Category created!")
            return redirect('product:categories')
        else:
            messages.error(request, form.errors)

    context = {
        'objs': categories,
        'category':category,
        'form':form,
        'page_obj':page_obj,
    }
    return render(request, 'product/categories/table.html', context)

@login_required(login_url='authentic:login')
def categoryDetail(request, pk):
    """
    Detail view of Category,
    Possibility to update Category Name
    """
    obj = get_object_or_404(Category, id=pk)

    category_products = get_products_by_category(obj)

    form = CategoryForm(instance=obj)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            messages.success(request, "Category Modified!")
            return redirect('product:category', obj.id)
        else:
            messages.error(request, form.errors)

    context = {
        'obj':obj,
        'category_products':category_products,
        'form':form,
    }
    return render(request, "product/categories/detail.html", context)

@login_required(login_url='authentic:login')
def categoryDelete(request, pk):
    """
    Delete Category
    """
    obj = get_object_or_404(Category, id=pk)
    if request.method == 'POST':
        obj.delete()
        messages.success(request, "Category Deleted!")
        return redirect('product:categories')
    return render(request, 'delete.html', {'obj':obj})

# Measurements
@login_required(login_url='authentic:login')
def measurementTable(request):
    """
    View Product Measurements,
    Contains a table with all existing Measurements,
    Possibility to create new Measurement
    Search on Navbar by: measure.
    """
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    measurements = Measurement.objects.filter(
        Q(measure__icontains=q)
    )

    page_obj = get_page_obj(measurements, request)
    
    form = MeasurementForm()
    if request.method == 'POST':
        form = MeasurementForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Measurement Created!")
            return redirect("product:measurements")
        else:
            messages.error(request, f'{form.errors}')

    context = {
        'objs' : measurements,
        'form' : form,
        'page_obj' : page_obj,
    }
    return render(request, 'product/measurements/table.html', context)

@login_required(login_url='authentic:login')
def measurementDetail(request, pk):
    """
    Detail view of Measurement,
    Possibility to update Measurement measure
    """
    measurement = get_object_or_404(Measurement, id=pk)

    form = MeasurementForm(instance=measurement)
    if request.method == 'POST':
        form = MeasurementForm(request.POST, instance=measurement)
        if form.is_valid():
            form.save()
            messages.success(request, "Measurement Modified!")
        else:
            messages.error(request, form.errors)

    context = {
        'obj':measurement,
        'form':form,
    }
    return render(request, "product/measurements/detail.html", context)

@login_required(login_url='authentic:login')
def measurementDelete(request, pk):
    """
    Delete Measurement
    """
    obj = get_object_or_404(Measurement, id=pk)
    if request.method == 'POST':
        obj.delete()
        messages.success(request, "Measurement Deleted!")
        return redirect('product:measurements')
    return render(request, 'delete.html', {'obj':obj})

src/product/templates/product/products/create-product-modal.html
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createModal">Create Product</h5>
                <button type="button" class="btn btn-warning" data-bs-dismiss="modal" aria-label="Close"><i
                        class="fa-solid fa-xmark"></i></button>
            </div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body row g-3">
                        <!-- Product Category -->
                        <div class="col-12">
                            <div class="form-floating">
                                <select id="product-category" class="form-select" name="category">
                                    <option selected>...</option>
                                    {% for choice in form.category.field.choices %}
                                    <option value="{{choice.0}}">{{choice.1}}</option>
                                    {% endfor %}
                                  </select>
                                  <label for="product-category">Category</label>
                            </div>
                          </div>
                             <!-- Product Name -->
                             <div class="col-md-9">
                                 <div class="form-floating">
                                     <input type="text" class="form-control" id="product-name" name="name">
                                     <label for="product-name">Name</label>
                                 </div>
                             </div>
                             <!-- Product Active -->
                             <div class="col">
                                 <div class="form-check">
                                     <input type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off" name="active">
                                     <label class="btn btn-outline-success" for="btn-check-outlined">Active</label><br>
                                 </div>
                             </div>
                        <!-- Product Image -->
                        <div class="input-group">
                            <input type="file" class="form-control" id="product-img" aria-describedby="product-img" aria-label="Upload" name="product_img">
                          </div>
                        <!-- Product Description -->
                        <div class="col-12">
                          <div class="form-floating">
                            <textarea class="form-control" placeholder="Describe the Product" id="product-description" name="description" style="height: 100px"></textarea>
                            <label for="product-description">Description</label>
                          </div>
                        </div>
                        <!-- Product Price -->
                        <div class="col-md-4">
                            <div class="input-group mb-3">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="product-price" name="price" aria-label="Euros">
                                    <label for="product-price">Price</label>
                                </div>
                                <span class="input-group-text">€</span>
                            </div>
                        </div>
                        <!-- Product Discount -->
                        <div class="col-md-4">
                            <div class="input-group mb-3">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="product-discount" name="discount" aria-label="%">
                                    <label for="product-discount">Discount</label>
                                </div>
                                <span class="input-group-text">%</span>
                            </div>
                        </div>
                        <!-- Product Measurement -->
                        <div class="col-md-4">
                            <div class="form-floating">
                                <select id="product-measurement" class="form-select" name="measurement">
                                    <option selected>...</option>
                                    {% for choice in form.measurement.field.choices %}
                                    <option value="{{choice.0}}">{{choice.1}}</option>
                                    {% endfor %}
                                  </select>
                                  <label for="product-measurement">Measurement</label>
                            </div>
                          </div>
                </div>
                <div class="modal-footer col-12">
                    <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Confirmar<span
                            class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                </div>
            </form>
        </div>
    </div>
</div>

src/product/templates/product/products/detail.html
{% extends 'main.html' %}
{% block title %}- Product {{obj.name}} {% endblock title %}

{% block content %}

{% include 'product/products/update-product-modal.html' %}

<main class="content p-2">
    <div class="container-xl">
        <!-- Title + Action -->
        <div class="row">
            <div class="col">
                <h4 class="title">
                    {{obj.name}}
                </h4>
            </div>
            <div class="col">
                <div class="action text-end">
                    <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#updateModal{{obj.id}}">
                        <i class="fa-solid fa-pen-to-square"></i>
                </div>
            </div>
        </div>
        <!--End Title + Action -->
        <hr>
        <!-- Product Info -->
        <div class="row">
            <div class="col d-flex">
                <div class="card flex-fill border-0">
                    <div class="card-body p-0 d-flex flex-fill">
                        <div class="row g-0 w-100">
                            <div class="col pt-4">
                                <div class="p-3 m-1">
                                    <h4 class="mt-2 p-2 text-center">
                                        <span class="badge text-bg-secondary">{{obj.category}}</span>
                                        <span class="badge text-bg-info">{{obj.measurement}}</span>
                                        {% if obj.active == True %}
                                        <span class="badge text-bg-success">Active</span>
                                        {% else %}
                                        <span class="badge text-bg-danger">Inactive</span>
                                        {% endif %}
                                    </h4>
                                        <div class="container pt-4">
                                            <table class="table table-striped table-bordered border-dark">
                                                <thead>
                                                    <tr class="table-dark text-white text-center">
    
                                                        <th scope="col">Price</th>
                                                        <th scope="col">Discount</th>
                                                        <th scope="col">Final Price</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr class="text-center">
                                                        <td>{{obj.price}} €</td>
                                                        <td>{{ obj.discount|default:"No discount" }} %</td>
                                                        <td><b>{{obj.final_price}} €</b></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="card text-bg-dark mb-3">
                                            <div class="card-header">Description</div>
                                            <div class="card-body">
                                              <p class="card-text">{{obj.description}}</p>
                                            </div>
                                        </div>                                                                  
                                </div>
                            </div>
                            <div class="col-md-4 align-self-center text-end">
                                <img src="{{obj.product_img.url}}" class="img-fluid illustration-img" alt="{{obj.name}} image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Product Info -->

        <!-- Stock pie chart -->
         <div class="row g-0 w-100">
            <div class="col-md-6 mb-2 d-flex flex-fill justify-content-center">
                {% include 'product/products/stock-pie-chart.html' %}
            </div>
            <div class="col-md-6 mb-2 d-flex flex-fill justify-content-center">
                {% include 'product/products/stock-pie-chart.html' %}
            </div>
         </div>

        <!-- Transactions Info -->
        {% include 'product/products/transactions-info.html' %}
        <!-- End Transactions Info -->
    </div>
</main>
{% endblock content %}

src/product/templates/product/products/table.html
{% extends 'main.html' %}
{% load product_extras %}
{% block title %}
- Product Table
{% endblock title %}

{% block content %}

{% include 'product/products/create-product-modal.html' %}

<main class="content p-2">
    <div class="container-xl">
        <!-- Title + Action -->
        <div class="row">
            <div class="col">
                <h4 class="title">
                    Products Table
                </h4>
            </div>
            <div class="col">
                <div class="action text-end">
                    <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#createModal">
                        <i class="fa-solid fa-folder-plus"></i>
                    </button>
                </div>
            </div>
        </div>
        <!-- End Title + Action -->
        <hr>
        <!-- Card with Table -->
        <div class="card border-0">
            <div class="d-flex px-4 mt-4">
                <table class="table table-striped table-bordered border-dark">
                    <thead>
                        <tr class="table-dark text-white text-center">
                            <th scope="col">#</th>
                            <th scope="col">{{ product|verbose_name:"name" }}</th>
                            <th scope="col">{{ product|verbose_name:"category" }}</th>
                            <th scope="col">{{ product|verbose_name:"active" }}</th>
                            <th scope="col">{{ product|verbose_name:"price" }}</th>
                            <th scope="col">{{ product|verbose_name:"discount" }}</th>
                            <th scope="col">Final Price</th>
                            <th scope="col">Activity</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for obj in page_obj %}
                        <tr class="text-center">
                            <th scope="row">{{ obj.id }}</th>
                            <th scope="row">{{ obj.name }}</th>
                            <th scope="row">{{ obj.category }}</th>
                            <th scope="row">
                            {% if obj.active %}
                            <span class="badge rounded-pill bg-success">
                                <i class="fa-regular fa-circle-check"></i>
                            </span>
                            {% else %}
                            <span class="badge rounded-pill bg-danger">
                                <i class="fa-regular fa-circle-xmark"></i>
                            </span>
                            {% endif %}
                            </th>
                            <th scope="row">{{ obj.price }} €</th>
                            <th scope="row">{{ obj.discount }} %</th>
                            <th scope="row">{{ obj.final_price }} €</th>
                            <td>
                                <!-- Detail -->
                                <a class="btn btn-sm btn-outline-success" href="{% url 'product:detail' obj.id %}">
                                    <i class="fa-solid fa-eye"></i>
                                </a>
                                <!-- Delete -->
                                <a class="btn btn-sm btn-outline-danger" href="{% url 'product:delete' obj.id %}">
                                    <i class="fa-solid fa-x"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- End Card with Table -->
        {% include 'pagination.html' %}
    </div>
</main>
{% endblock content %}

src/product/templates/product/products/transactions-info.html
<div class="row mt-2">
    <div class="col">
        <div class="card border-0">
            <div class="card-body">
                <h5 class="card-title mb-2 text-muted">
                    Sales
                </h5>
                <hr>
                <ul class="list-group">
                    {% for sale in sales %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">
                                <a class="text-decoration-none text-secondary" href="{% url 'partners:client' sale.client.id %}">{{sale.client.name}}</a> - 
                                <a class="text-decoration-none text-success" href="{% url 'transactions:sale' sale.transaction_id %}">{{sale.transaction_id}}</a>
                            </div>
                            <small class="text-muted">{{sale.transaction_date}}</small>
                          <span class="badge bg-success rounded-pill">{{sale.quantity}} {{obj.measurement}}</span>
                        </div>
                        <span class="badge bg-secondary rounded-pill">{{sale.final_price}} €</span>
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card border-0">
            <div class="card-body">
                <h5 class="card-title mb-2 text-muted">
                    Purchases
                </h5>
                <hr>
                <ul class="list-group">
                    {% for purchase in purchases %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="ms-2 me-auto">
                                <div class="fw-bold">
                                    <a class="text-decoration-none text-secondary" href="{% url 'partners:supplier' purchase.supplier.id %}">{{purchase.supplier.name}}</a> - 
                                    <a class="text-decoration-none text-warning" href="{% url 'transactions:purchase' purchase.transaction_id %}">{{purchase.transaction_id}}</a>
                                </div>
                                <small class="text-muted">{{purchase.transaction_date}}</small>
                                <span class="badge bg-warning rounded-pill">{{purchase.quantity}} {{obj.measurement}}</span>
                            </div>
                          <span class="badge bg-secondary rounded-pill">{{purchase.final_price}} €</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>